version: "3"
services:
    ubuntu:
        image: zenbot-1
        container_name: zenbot-test-1
        command: sleep infinity
        environment:
            DISCORD_TOKEN: "${DISCORD_TOKEN}"

    watchtower:
        image: containrrr/watchtower
        container_name: watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: zenbot
